module.exports = [
  { id: 0,  title: "Prolog",                       start: 1,   end: 3   },
  { id: 1,  title: "Släktarvet",                    start: 4,   end: 6   },
  { id: 2,  title: "Välfärdets barn",               start: 7,   end: 27  },
  { id: 3,  title: "Mötet med Carsten",             start: 28,  end: 39  },
  { id: 4,  title: "Lanthandeln i Ekskogen",        start: 40,  end: 55  },
  { id: 5,  title: "J'accuse! – Moderna Museet",    start: 56,  end: 70  },
  { id: 6,  title: "Vägen till Amerika",            start: 71,  end: 83  },
  { id: 7,  title: "San Francisco & poesins väst",  start: 84,  end: 95  },
  { id: 8,  title: "Genom öken och berg",           start: 96,  end: 110 },
  { id: 9,  title: "Återkomst till Sverige",        start: 111, end: 120 },
  { id: 10, title: "Film och Gösta Ekman",          start: 121, end: 138 },
  { id: 11, title: "Brödskrivaren",                 start: 139, end: 153 },
  { id: 12, title: "Sibirsk väg",                   start: 154, end: 165 },
  { id: 13, title: "Beck växer fram",               start: 166, end: 180 },
  { id: 14, title: "Karriär och självinblick",      start: 181, end: 193 },
  { id: 15, title: "Beck triumferar",               start: 194, end: 210 },
  { id: 16, title: "Karriärbalansen",               start: 211, end: 220 },
  { id: 17, title: "Operan och världens möte",      start: 221, end: 248 },
  { id: 18, title: "Beck till sist",                start: 249, end: 275 },
  { id: 19, title: "Epilog",                        start: 276, end: 276 },
];
